### ISSUE TITLE
Build problems on aarch64

### ISSUE THREAD

**Issue by ccoupe** [sheosi/lily#409]
Hi,  I have a Raspberry pi 4 running 64bit Raspberry OS and the `cargo build` for installation fails with 
```rs
   Compiling opusic-sys v0.3.6
error: This macro cannot be used on the current target.
                                   You can prevent it from being used in other architectures by
                                   guarding it behind a cfg(any(target_arch = "x86", target_arch = "x86_64")).
   --> /home/ccoupe/.cargo/registry/src/github.com-1ecc6299db9ec823/opusic-sys-0.3.6/build.rs:115:13
    |
115 |         if !std::is_x86_feature_detected!("avx") {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `std::is_x86_feature_detected` (in Nightly builds, run with -Z macro-backtrace for more info)
```
There are many of these errors in this module and several other modules.  I don't know enough Rust to determine if this is a Rust problem or if it's a Lily problem, where to fix it.

**Comment by sheosi** [comment]
I can reproduce it too. This is not on Lily itself but rather on a depenendency "opusic", I'll move the dependency to another library.

**Comment by sheosi** [comment]
Give it a try now, fortunately the dependency blocking the compilation wasnt needed at all.

**Comment by sheosi** [comment]
Give it a try now the dependency that producedc the error wasn't necessary at all.

**Comment by ccoupe** [comment]
Yes, I am able to build lily. Thank you.

**Comment by ccoupe** [comment]
It took a while to build all that on pi4 with ssd.
